### ISSUE TITLE
No part number for the FMC connector given in schematic

### ISSUE THREAD

**Issue by darkstar007** [TommyE79/SITLINV-FPGA_Board#4]
Hi,

I'm looking for the part number of the FMC connector used (actually, what I really want is the part number of a suitable connector that will plug into it!). Unfortunately nothing is given in the schematic. I assume its a Samtec part - but there are many options.....

(I couldn't see any other reference to the connector other than the pin-out given in the PIN.xlsx file.)

Thanks,
Matt.

**Comment by TommyE79** [comment]
Hi Matt,

I'm not the direct creator of this board, but assisted to get this GitHub repo up.
So, the creator of the board, I'm still in contact with this guy, told me, he's using the connectors as mentioned on the xilinx site.
So it should be 2x 40-pin samtec female connectors, 0.8mm pitch as described in the schematics.

I hope this will help you.

Regards
Thomas

**Comment by mobilinkd** [comment]
It should be a standard LPC FMC Samtec connector. They can be found on Digikey and Mouser. I'm always amazed at how much these specialized connectors cost.

https://www.fmchub.com/faq/ -- you will want an LPC mezzanine connector.

If you can get by with the lower pin count, the 80-pin BTB connector is a much cheaper option.

**Comment by darkstar007** [comment]
Yeah, that's what I thought - but thought given the prices it would be good to double check!

**Comment by TommyE79** [comment]
> Yeah, that's what I thought - but thought given the prices it would be good to double check!

I agree in this point!
